#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend edungaira.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        serve 200504-web-01 35.168.8.157.0:80
        server 200504-web-02 34.201.165.197.0:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
